version: "3.8"

services:
  psql_db:
    image: postgres:latest
    container_name: psql_db
    env_file:
      - .env
    ports:
      - "${PSQL_PORT}:${PSQL_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    env_file:
      - .env
    build:
      context: .
volumes:
     dbdata: